import { Link } from 'react-router-dom';
import { SKYWEB_PRODUCT_NAME } from '../constants/branding.js';

export default function Home() {
  return (
    <>
      <section className="skyweb-hero skyweb-home-hero skyweb-screenshot-section">
        <div className="skyweb-hero-content">
          <div className="skyweb-kicker">Sky ecosystem analytics layer</div>
          <h1>{SKYWEB_PRODUCT_NAME}: living macro data and public proof of work.</h1>
          <p>
            SkyWeb Analytics is the presentation layer for curated SkyServer data. It consumes live
            public macro APIs and turns the SkyServer data plane into a browsable analytics surface
            with charts, story cards, drilldowns, and a staged member layer.
          </p>
          <div className="skyweb-hero-actions">
            <Link className="btn skyweb-btn-primary" to="/macro">
              Open macro dashboard
            </Link>
            <Link className="btn skyweb-btn-ghost" to="/macro/views">
              Browse data views
            </Link>
            <Link className="btn skyweb-btn-ghost" to="/dashboard">
              Personal dashboard
            </Link>
          </div>
        </div>
        <div className="skyweb-hero-panel skyweb-status-panel">
          <div className="skyweb-panel-label">SkyWeb Analytics Phase 7.3</div>
          <h2>Personal analytics layer online</h2>
          <ul>
            <li>Public macro dashboard is live and screenshot-ready</li>
            <li>Metric-selectable chart drilldowns are online</li>
            <li>Macro overview now guides visitors through data stories</li>
            <li>Saved views now compose a private member dashboard</li>
          </ul>
        </div>
      </section>

      <section
        className="skyweb-proof-strip skyweb-screenshot-section"
        aria-label="SkyWeb Analytics proof points"
      >
        <article>
          <span>Control plane</span>
          <strong>SkyServer-backed</strong>
          <p>Public APIs are curated from the private ingestion, access, and automation layer.</p>
        </article>
        <article>
          <span>Analytics surface</span>
          <strong>Live macro views</strong>
          <p>
            Dashboards, catalogs, indicators, tables, and trend previews are wired to real data.
          </p>
        </article>
        <article>
          <span>Member runway</span>
          <strong>Auth prepared</strong>
          <p>
            App-scoped SkyWeb Analytics login powers saved dashboards, preferences, and watchlists.
          </p>
        </article>
      </section>

      <section className="skyweb-section-grid skyweb-home-grid">
        <article className="skyweb-card">
          <div className="skyweb-card-kicker">Data plane</div>
          <h2>Curated macro views</h2>
          <p>
            Explore inflation, growth, labor, rates, liquidity, housing, and U.S./Canada comparison
            views generated by the SkyServer macro layer.
          </p>
          <Link className="skyweb-card-link" to="/macro/views">
            Browse views →
          </Link>
        </article>
        <article className="skyweb-card">
          <div className="skyweb-card-kicker">Dashboard layer</div>
          <h2>Built for decisions</h2>
          <p>
            The dashboard now combines signal cards, category lanes, regional coverage, latest data,
            and interactive chart drilldowns.
          </p>
          <Link className="skyweb-card-link" to="/macro">
            Open overview →
          </Link>
        </article>
        <article className="skyweb-card">
          <div className="skyweb-card-kicker">Future auth</div>
          <h2>Prepared for SkyWeb Analytics users</h2>
          <p>
            SkyServer now supports application-scoped auth, giving SkyWeb Analytics a clean boundary
            for user profiles, personalization, alerts, and saved views.
          </p>
          <Link className="skyweb-card-link" to="/account">
            Open account →
          </Link>
        </article>
      </section>
    </>
  );
}
