import { Link } from 'react-router-dom';

export default function Home() {
  return (
    <>
      <section className="skyweb-hero skyweb-home-hero">
        <div className="skyweb-hero-content">
          <div className="skyweb-kicker">Sky ecosystem public layer</div>
          <h1>Macro dashboards, living data, and public proof of work.</h1>
          <p>
            SkyWeb is the presentation layer for curated SkyServer data. It now consumes live public
            macro APIs and turns the SkyServer data plane into a browsable analytics surface.
          </p>
          <div className="skyweb-hero-actions">
            <Link className="btn skyweb-btn-primary" to="/macro">
              Open macro dashboard
            </Link>
            <Link className="btn skyweb-btn-ghost" to="/macro/views">
              Browse data views
            </Link>
          </div>
        </div>
        <div className="skyweb-hero-panel skyweb-status-panel">
          <div className="skyweb-panel-label">Phase 9.2</div>
          <h2>Dashboard layer online</h2>
          <ul>
            <li>SkyServer public macro bridge connected</li>
            <li>Live macro overview dashboard staged</li>
            <li>View cards enriched with coverage metadata</li>
            <li>Reusable UI components now in place</li>
          </ul>
        </div>
      </section>

      <section className="skyweb-section-grid skyweb-home-grid">
        <article className="skyweb-card">
          <div className="skyweb-card-kicker">Data plane</div>
          <h2>Curated macro views</h2>
          <p>
            Explore inflation, growth, labor, rates, liquidity, housing, and U.S./Canada comparison
            views generated by the SkyServer macro layer.
          </p>
          <Link className="skyweb-card-link" to="/macro/views">
            Browse views →
          </Link>
        </article>
        <article className="skyweb-card">
          <div className="skyweb-card-kicker">Dashboard layer</div>
          <h2>Built for decisions</h2>
          <p>
            The first dashboard pass focuses on clean cards, fast filtering, latest values, and
            table previews before charts and saved dashboards arrive later.
          </p>
          <Link className="skyweb-card-link" to="/macro">
            Open overview →
          </Link>
        </article>
        <article className="skyweb-card">
          <div className="skyweb-card-kicker">Future auth</div>
          <h2>Prepared for SKYWEB users</h2>
          <p>
            SkyServer now supports application-scoped auth, giving SkyWeb a clean future boundary
            for user profiles, personalization, alerts, and saved views.
          </p>
          <Link className="skyweb-card-link" to="/macro/indicators">
            Inspect indicators →
          </Link>
        </article>
      </section>
    </>
  );
}
